// <auto-generated />
using System;
using AtomicSeller.Models.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace AtomicSeller.Migrations
{
    [DbContext(typeof(ASTRDEntities))]
    partial class JobsContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.2");

            modelBuilder.Entity("AtomicSeller.Models.jobs", b =>
                {
                    b.Property<string>("Category")
                        .HasColumnType("nvarchar(max)");

                    b.Property<TimeSpan?>("DailyEndTime")
                        .HasColumnType("time");

                    b.Property<TimeSpan?>("DailyStartTime")
                        .HasColumnType("time");

                    b.Property<string>("Enabled")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("JobID")
                        .HasColumnType("int");

                    b.Property<string>("JobName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<TimeSpan?>("JobPeriod")
                        .HasColumnType("time");

                    b.Property<DateTime?>("LastExecutionTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Repeat")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("TenantID")
                        .HasColumnType("int");

                    b.Property<string>("WebServiceOutput")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("WebserviceCarrierServiceKey")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("WebserviceKey")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("WebserviceReportingKey")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("WebserviceStoreKey")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("WebserviceWMSKey")
                        .HasColumnType("nvarchar(max)");

                    b.ToTable("jobs");
                });
#pragma warning restore 612, 618
        }
    }
}
